proxy:
  ssl: true
  host: eaddb.lyrasistechnology.org
  app_port: 3000

servers:
  web:
    hosts:
      - eaddb.lyrasistechnology.org
    env:
      JOB_CONCURRENCY: 2
      SOLID_QUEUE_IN_PUMA: true
      WEB_CONCURRENCY: 2
