production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  get_records_from_sources:
    class: GetRecordsFromSourcesJob
    schedule: "0 * * * *"
  session_expiration:
    command: "Session.sweep"
    schedule: every hour
